### ISSUE TITLE
异步启动模块优化开屏性能？

### ISSUE THREAD

**Issue by jseanj** [RyanLeeLY/TinyPart#1]
即使isAsync置为YES，但代码都是在主线程中执行，还是串行执行，只是先后顺序的问题，实际并不会优化开屏性能吧

**Comment by RyanLeeLY** [comment]
可以让这些模块进入到异步等待的状态，从而确保首屏UI可以优先出现。你可以尝试在`moduleDidLoad:`方法中加入`sleep(10)`这样的模拟耗时操作，来感受一下异步和同步的区别。

**Comment by jseanj** [comment]
嗯，我理解你的意思，如果首屏UI依赖的数据是从网络下载或者从磁盘读取的话，其实设置异步的模块还是有可能在UI渲染之前执行，这样就会阻塞住UI渲染，所以我理解真正异步的话还是放到子线程中执行。

**Comment by RyanLeeLY** [comment]
> 嗯，我理解你的意思，如果首屏UI依赖的数据是从网络下载或者从磁盘读取的话，其实设置异步的模块还是有可能在UI渲染之前执行，这样就会阻塞住UI渲染，所以我理解真正异步的话还是放到子线程中执行。

嗯，是这样的，我们在这里主要考虑的还是一些简单开屏异步优化。对于你所描述的网络加载或者磁盘读写这样的场景，我们考虑的是程序员在coding实现过程中就应该交到子线程，而不是通过框架来完成。
